version: "3.3"
services:
  pgsync:
    build:
      context: ../pgsync/docker
      dockerfile: Dockerfile
    command: sh ./runserver.sh
    sysctls:
      - net.ipv4.tcp_keepalive_time=200
      - net.ipv4.tcp_keepalive_intvl=200
      - net.ipv4.tcp_keepalive_probes=5
    labels:
      org.label-schema.name: "pgsync"
      org.label-schema.description: "Postgres to elasticsearch sync"
      com.label-schema.service-type: "daemon"
    depends_on:
      - db-autoparts
      - redis
networks:
  inbound: